// Booking System — Cross-device sync via Google Apps Script                                                                                                                                                                           
                                                        
  const PREFIX = 'booking_';                                                                                                                                                                                                             
                                                                                                                                                                                                                                         
  function doPost(e) {                                                                                                                                                                                                                   
    try {                                                                                                                                                                                                                                
      const payload = JSON.parse(e.postData.contents);                                                                                                                                                                                   
                                                                                   
      // Save bookings for a week                                                                                                                                                                                                        
      if (payload.action === 'saveBookings' && payload.weekKey) {                                                                                                                                                                        
        const key = PREFIX + payload.weekKey;                                                                                                                                                                                            
        PropertiesService.getScriptProperties().setProperty(key, JSON.stringify(payload.bookings));                                                                                                                                      
        return ContentService.createTextOutput(JSON.stringify({ status: 'ok' }))                                                                                                                                                         
          .setMimeType(ContentService.MimeType.JSON);                              
      }                                                     
                                                                                                                                                                                                                                         
      return ContentService.createTextOutput(JSON.stringify({ status: 'unknown_action' }))                                                                                                                                               
        .setMimeType(ContentService.MimeType.JSON);                                                                                                                                                                                      
    } catch (err) {                                                                                                                                                                                                                      
      return ContentService.createTextOutput(JSON.stringify({ status: 'error', message: err.message }))                                                                                                                                  
        .setMimeType(ContentService.MimeType.JSON);                                                                                                                                                                                      
    }                                                                                                                                                                                                                                    
  }                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                         
  function doGet(e) {                                                                                                                                                                                                                    
    try {                                                                                                                                                                                                                                
      const action = e.parameter.action;                                                                                                                                                                                                 
                                                                                                                                                                                                                                         
      // Load bookings for a week                                                                                                                                                                                                        
      if (action === 'loadBookings' && e.parameter.weekKey) {                                                                                                                                                                            
        const key = PREFIX + e.parameter.weekKey;                                                                                                                                                                                        
        const raw = PropertiesService.getScriptProperties().getProperty(key);                                                                                                                                                            
        const bookings = raw ? JSON.parse(raw) : {};                                                                                                                                                                                     
        return ContentService.createTextOutput(JSON.stringify({ bookings }))
          .setMimeType(ContentService.MimeType.JSON);                                                                                                                                                                                    
      }                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                         
      // List all stored weeks (for debugging)                                                                                                                                                                                           
      if (action === 'list') {                                                                                                                                                                                                           
        const props = PropertiesService.getScriptProperties().getProperties();                                                                                                                                                           
        const weeks = Object.keys(props).filter(k => k.startsWith(PREFIX)).map(k => k.slice(PREFIX.length));                                                                                                                             
        return ContentService.createTextOutput(JSON.stringify({ weeks }))                                                                                                                                                                
          .setMimeType(ContentService.MimeType.JSON);                                                                                                                                                                                    
      }                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                         
      return ContentService.createTextOutput(JSON.stringify({ status: 'unknown_action' }))                                                                                                                                               
        .setMimeType(ContentService.MimeType.JSON);                                
    } catch (err) {                                                                                                                                                                                                                      
      return ContentService.createTextOutput(JSON.stringify({ status: 'error', message: err.message }))                                                                                                                                  
        .setMimeType(ContentService.MimeType.JSON);                                                                                                                                                                                      
    }                                                                                                                                                                                                                                    
  }