"""Data model for Spelling Tracker — pupils, rules, weeks."""

DEFAULT_RULES = [
    {"id":"y1s1","year":"Year 1","step":1,"title":"Year 1 - Step 1: Words ending in 'ff', 'll', 'ss', 'zz' and 'ck'","explanation":"When a short vowel sound is followed by an /f/, /l/, /s/ or /z/ sound at the end of a word, we usually double the consonant. The /k/ sound at the end of a short-vowel word is always spelled 'ck'.","words":["bell","kiss","clock","puff","buzz"]},
    {"id":"y1s2","year":"Year 1","step":2,"title":"Year 1 - Step 2: Words with the /k/ sound spelled 'k' and 'nk'","explanation":"The /k/ sound can be spelled with a 'k', especially before 'e', 'i' or a consonant.","words":["kit","mask","bank","pink","skin"]},
    {"id":"y1s3","year":"Year 1","step":3,"title":"Year 1 - Step 3: Words with the 'tch' trigraph","explanation":"The letters 't', 'c' and 'h' make the /ch/ sound and this pattern is used after a short vowel.","words":["catch","fetch","hutch","match","patch"]},
    {"id":"y1s4","year":"Year 1","step":4,"title":"Year 1 - Step 4: Adding '-s' and '-es' to make plurals","explanation":"To make most words plural, we add '-s'. When a word ends in 's', 'x', 'sh', 'ch' or 'z', we add '-es'.","words":["cars","boats","boxes","buses","wishes"]},
    {"id":"y1s5","year":"Year 1","step":5,"title":"Year 1 - Step 5: Adding the suffixes '-ing' and '-ed'","explanation":"'-ing' shows something is happening now and '-ed' shows it has already happened.","words":["jumping","buzzed","walking","played","running"]},
    {"id":"y1s6","year":"Year 1","step":6,"title":"Year 1 - Step 6: Adding the prefix 'un-' and suffixes '-er' and '-est'","explanation":"'un-' means 'not' or 'opposite'. '-er' and '-est' are added to adjectives to compare things.","words":["unhappy","undo","fresher","hardest","bravest"]},
    {"id":"y1s7","year":"Year 1","step":7,"title":"Year 1 - Step 7: Compound words and words with unstressed vowels","explanation":"A compound word is made by joining two smaller words together.","words":["football","bedroom","sunset","carrot","balloon"]},
    {"id":"y1s8","year":"Year 1","step":8,"title":"Year 1 - Step 8: Words with the digraphs 'ai' and 'oi'","explanation":"'ai' makes the /ay/ sound and 'oi' makes the /oy/ sound.","words":["rain","train","coin","point","snail"]},
    {"id":"y1s9","year":"Year 1","step":9,"title":"Year 1 - Step 9: Words with the digraphs 'ay' and 'oy'","explanation":"'ay' makes the /ay/ sound and 'oy' makes the /oy/ sound, usually at the end of a word.","words":["day","play","toy","boy","enjoy"]},
    {"id":"y1s10","year":"Year 1","step":10,"title":"Year 1 - Step 10: Words with the split digraph 'a_e'","explanation":"The 'a_e' pattern makes a long /ay/ sound — the 'e' at the end is silent.","words":["make","came","same","cake","name"]},
    {"id":"y1s11","year":"Year 1","step":11,"title":"Year 1 - Step 11: Words with the split digraph 'e_e'","explanation":"The split digraph 'e_e' makes a long /ee/ sound.","words":["these","theme","complete","scene","gene"]},
    {"id":"y1s12","year":"Year 1","step":12,"title":"Year 1 - Step 12: Words with the split digraph 'i_e'","explanation":"The split digraph 'i_e' makes a long /igh/ sound.","words":["ride","like","time","smile","white"]},
    {"id":"y1s13","year":"Year 1","step":13,"title":"Year 1 - Step 13: Words with the split digraph 'o_e'","explanation":"The split digraph 'o_e' makes a long /oa/ sound.","words":["home","hope","spoke","phone","bone"]},
    {"id":"y1s14","year":"Year 1","step":14,"title":"Year 1 - Step 14: Words with the split digraph 'u_e'","explanation":"The split digraph 'u_e' makes a long /yoo/ or /oo/ sound.","words":["tune","rude","flute","cube","June"]},
    {"id":"y1s15","year":"Year 1","step":15,"title":"Year 1 - Step 15: Words with the digraph 'ar'","explanation":"The digraph 'ar' makes a long /ar/ sound.","words":["car","park","dark","star","sharp"]},
    {"id":"y1s16","year":"Year 1","step":16,"title":"Year 1 - Step 16: Words with the digraph 'ee'","explanation":"The digraph 'ee' always makes a long /ee/ sound.","words":["tree","feel","meet","green","seed"]},
    {"id":"y1s17","year":"Year 1","step":17,"title":"Year 1 - Step 17: Words where 'ea' makes an /ee/ sound","explanation":"The digraph 'ea' can make a long /ee/ sound.","words":["reach","teach","leaf","beach","team"]},
    {"id":"y1s18","year":"Year 1","step":18,"title":"Year 1 - Step 18: Words where 'ea' makes an /e/ sound","explanation":"In some words, the digraph 'ea' makes a short /e/ sound.","words":["head","bread","dead","instead","spread"]},
    {"id":"y1s19","year":"Year 1","step":19,"title":"Year 1 - Step 19: Words where 'er' is stressed","explanation":"When 'er' is stressed, it makes a clear /er/ sound.","words":["her","verb","term","serve","fern"]},
    {"id":"y1s20","year":"Year 1","step":20,"title":"Year 1 - Step 20: Words where 'er' is unstressed","explanation":"When 'er' is unstressed, it makes a quieter /uh/ sound (schwa).","words":["summer","sister","river","dinner","better"]},
    {"id":"y1s21","year":"Year 1","step":21,"title":"Year 1 - Step 21: Words with the digraphs 'ir' and 'ur'","explanation":"The digraphs 'ir' and 'ur' both make the same /er/ sound.","words":["girl","first","bird","turn","hurt"]},
    {"id":"y1s22","year":"Year 1","step":22,"title":"Year 1 - Step 22: Words where 'oo' makes an /oo/ sound","explanation":"The digraph 'oo' can make a long /oo/ sound.","words":["moon","food","spoon","blue","flew"]},
    {"id":"y1s23","year":"Year 1","step":23,"title":"Year 1 - Step 23: Words where 'oo' makes an /u/ sound","explanation":"The digraph 'oo' can make a shorter /u/ sound.","words":["book","cook","look","wood","stood"]},
    {"id":"y1s24","year":"Year 1","step":24,"title":"Year 1 - Step 24: Words with 'oa' and 'oe'","explanation":"The digraphs 'oa' and 'oe' both make a long /oa/ sound.","words":["goat","road","toe","boat","float"]},
    {"id":"y1s25","year":"Year 1","step":25,"title":"Year 1 - Step 25: Words where 'ou' makes an /ow/ sound","explanation":"The digraph 'ou' can make an /ow/ sound.","words":["out","shout","found","round","proud"]},
    {"id":"y1s26","year":"Year 1","step":26,"title":"Year 1 - Step 26: Words where 'ow' makes /ow/ or /oa/","explanation":"The digraph 'ow' can make two different sounds.","words":["down","town","snow","blow","grow"]},
    {"id":"y1s27","year":"Year 1","step":27,"title":"Year 1 - Step 27: Words ending in 'y' /ee/ and 've' /v/","explanation":"Many words end in 'y' making an /ee/ sound. The /v/ sound at the end of a word is always spelled 've'.","words":["happy","very","give","have","love"]},
    {"id":"y1s28","year":"Year 1","step":28,"title":"Year 1 - Step 28: Words with 'ue' and 'ew'","explanation":"The digraphs 'ue' and 'ew' both make a /yoo/ or /oo/ sound.","words":["clue","true","new","drew","flew"]},
    {"id":"y1s29","year":"Year 1","step":29,"title":"Year 1 - Step 29: Words where 'ie' makes an /igh/ sound","explanation":"The digraph 'ie' can make a long /igh/ sound at the end of a word.","words":["lie","pie","tie","fried","dried"]},
    {"id":"y1s30","year":"Year 1","step":30,"title":"Year 1 - Step 30: Words where 'ie' makes an /ee/ sound","explanation":"The digraph 'ie' can also make a long /ee/ sound.","words":["chief","thief","piece","field","shield"]},
    {"id":"y1s31","year":"Year 1","step":31,"title":"Year 1 - Step 31: Words with the trigraph 'igh'","explanation":"The trigraph 'igh' makes a long /igh/ sound. The 'gh' is always silent.","words":["night","light","bright","fight","might"]},
    {"id":"y1s32","year":"Year 1","step":32,"title":"Year 1 - Step 32: Words with 'or' and 'ore'","explanation":"The digraph 'or' makes an /or/ sound and the trigraph 'ore' makes the same sound.","words":["north","morning","more","shore","before"]},
    {"id":"y1s33","year":"Year 1","step":33,"title":"Year 1 - Step 33: Words with 'aw' and 'au'","explanation":"The digraphs 'aw' and 'au' both make an /or/ sound.","words":["saw","crawl","August","author","launch"]},
    {"id":"y1s34","year":"Year 1","step":34,"title":"Year 1 - Step 34: Words with 'air' and 'ear'","explanation":"The trigraph 'air' makes an /air/ sound and 'ear' makes an /ear/ sound.","words":["chair","pair","fairy","ear","hear"]},
    {"id":"y1s35","year":"Year 1","step":35,"title":"Year 1 - Step 35: Words where 'ear' and 'are' make /air/","explanation":"In some words, 'ear' and 'are' make an /air/ sound.","words":["bear","wear","bare","dare","care"]},
    {"id":"y1s36","year":"Year 1","step":36,"title":"Year 1 - Step 36: Words with 'ph' and 'wh'","explanation":"The digraph 'ph' makes an /f/ sound and 'wh' usually makes a /w/ sound.","words":["dolphin","elephant","phone","wheel","when"]},
    # Year 2
    {"id":"y2s0","year":"Year 2","step":0,"title":"Year 2 - Step 0: Doubling consonants before -ED","explanation":"Words with a short vowel sound before the final consonant need that consonant doubled before adding -ED.","words":["patted","stopped","clapped","dragged","hummed"]},
    {"id":"y2s1","year":"Year 2","step":1,"title":"Year 2 - Step 1: Words where 'dge' makes a /j/ sound","explanation":"The trigraph 'dge' makes a /j/ sound.","words":["badge","edge","bridge","dodge","fudge","ridge","smudge","judge","wedge","lodge"]},
    {"id":"y2s2","year":"Year 2","step":2,"title":"Year 2 - Step 2: Words where 'ge' makes a /j/ sound","explanation":"The letters 'ge' make a /j/ sound at the end of a word or before a consonant.","words":["change","strange","range","hinge","fringe"]},
    {"id":"y2s3","year":"Year 2","step":3,"title":"Year 2 - Step 3: Words where 'g' makes a /j/ sound","explanation":"Before 'e', 'i' or 'y', the letter 'g' can make a soft /j/ sound.","words":["gem","giant","giraffe","engine","gentle"]},
    {"id":"y2s5","year":"Year 2","step":5,"title":"Year 2 - Step 5: Words with silent 'kn' and 'gn'","explanation":"In some words, 'kn' or 'gn' at the start have a silent first letter.","words":["knock","know","knee","gnome","gnat"]},
    {"id":"y2s6","year":"Year 2","step":6,"title":"Year 2 - Step 6: Challenge Words","explanation":"These words have irregular spelling patterns.","words":["door","floor","find","kind","children"]},
    {"id":"y2s7","year":"Year 2","step":7,"title":"Year 2 - Step 7: Words with silent 'wr'","explanation":"At the start of some words, 'wr' makes a /r/ sound — the 'w' is silent.","words":["write","wrap","wrong","wren","wrist"]},
    {"id":"y2s10","year":"Year 2","step":10,"title":"Year 2 - Step 10: Words ending in 'al'","explanation":"Some words end in 'al' making an /ul/ sound.","words":["metal","capital","animal","local","several"]},
    {"id":"y2s11","year":"Year 2","step":11,"title":"Year 2 - Step 11: Words ending in 'il'","explanation":"Some words end in 'il' making an /ul/ sound.","words":["pencil","fossil","basil","lentil","nostril"]},
    {"id":"y2s12","year":"Year 2","step":12,"title":"Year 2 - Step 12: Challenge Words","explanation":"These words do not follow common spelling rules.","words":["wild","climb","most","both","cold"]},
    {"id":"y2s13","year":"Year 2","step":13,"title":"Year 2 - Step 13: Words where 'y' makes an /igh/ sound","explanation":"At the end of a short word, 'y' makes a long /igh/ sound.","words":["cry","fly","try","shy","sky"]},
    {"id":"y2s14","year":"Year 2","step":14,"title":"Year 2 - Step 14: Adding '-es' to words ending in 'y'","explanation":"When a word ends in consonant+'y', the 'y' changes to 'i' before adding '-es'.","words":["flies","babies","carries","stories","cherries"]},
    {"id":"y2s15","year":"Year 2","step":15,"title":"Year 2 - Step 15: Adding '-ed' to words ending in 'y'","explanation":"When a word ends in consonant+'y', the 'y' changes to 'i' before adding '-ed'.","words":["copied","replied","spied","fried","tried"]},
    {"id":"y2s16","year":"Year 2","step":16,"title":"Year 2 - Step 16: Adding '-er'/'-est' to words ending in 'y'","explanation":"The 'y' changes to 'i' before adding '-er' or '-est'.","words":["happier","happiest","tidier","tidiest","prettier"]},
    {"id":"y2s17","year":"Year 2","step":17,"title":"Year 2 - Step 17: Adding '-ing' to words ending in 'e'","explanation":"We remove the silent 'e' before adding '-ing'.","words":["hiking","smiling","writing","making","surprising"]},
    {"id":"y2s18","year":"Year 2","step":18,"title":"Year 2 - Step 18: Challenge Words","explanation":"These words have irregular patterns.","words":["every","even","beautiful","break","steak"]},
    {"id":"y2s19","year":"Year 2","step":19,"title":"Year 2 - Step 19: Adding suffixes to words ending in 'e'","explanation":"The silent 'e' is removed before adding '-er', '-est' or '-ed'.","words":["nicer","nicest","hoped","largest","braver"]},
    {"id":"y2s20","year":"Year 2","step":20,"title":"Year 2 - Step 20: Doubling consonants before '-ing'","explanation":"We double the final consonant before adding '-ing' in single-syllable words with short vowels.","words":["running","hopping","sitting","clapping","stopping"]},
    {"id":"y2s21","year":"Year 2","step":21,"title":"Year 2 - Step 21: Doubling consonants before '-ed'","explanation":"We double the final consonant before adding '-ed' in single-syllable words with short vowels.","words":["patted","drummed","dropped","clapped","hummed"]},
    {"id":"y2s22","year":"Year 2","step":22,"title":"Year 2 - Step 22: Words where 'a' makes an /or/ sound","explanation":"In some words, 'a' makes an /or/ sound, usually before 'll' or 'lk'.","words":["all","ball","call","walk","always"]},
    {"id":"y2s23","year":"Year 2","step":23,"title":"Year 2 - Step 23: Words where 'o' makes an /u/ sound","explanation":"In some common words, 'o' makes a short /u/ sound.","words":["other","mother","some","money","done"]},
    {"id":"y2s24","year":"Year 2","step":24,"title":"Year 2 - Step 24: Challenge Words","explanation":"These words have irregular patterns.","words":["last","father","class","path","bath"]},
    {"id":"y2s25","year":"Year 2","step":25,"title":"Year 2 - Step 25: Words where 'ey' makes an /ee/ sound","explanation":"The digraph 'ey' can make an /ee/ sound at the end of words.","words":["key","monkey","donkey","journey","valley"]},
    {"id":"y2s26","year":"Year 2","step":26,"title":"Year 2 - Step 26: Words where 'a' makes an /o/ sound","explanation":"After 'w', the letter 'a' can make a short /o/ sound.","words":["want","watch","wander","quality","squash"]},
    {"id":"y2s27","year":"Year 2","step":27,"title":"Year 2 - Step 27: Words where 'or' and 'ar' make /er/","explanation":"After 'w', 'or' and 'ar' can make an /er/ sound.","words":["word","work","world","warm","war"]},
    {"id":"y2s29","year":"Year 2","step":29,"title":"Year 2 - Step 29: Words ending in '-ment' and '-ness'","explanation":"'-ment' turns a verb into a noun. '-ness' turns an adjective into a noun.","words":["enjoyment","darkness","kindness","adjustment","careful"]},
    {"id":"y2s30","year":"Year 2","step":30,"title":"Year 2 - Step 30: Words ending in '-ful', '-less' and '-ly'","explanation":"'-ful' means full of, '-less' means without, '-ly' turns adjectives into adverbs.","words":["careful","hopeless","boldly","thankful","spotless"]},
    {"id":"y2s31","year":"Year 2","step":31,"title":"Year 2 - Step 31: Homophones","explanation":"Homophones sound the same but have different spellings and meanings.","words":["there","their","here","hear","see"]},
    {"id":"y2s33","year":"Year 2","step":33,"title":"Year 2 - Step 33: Words ending in '-tion'","explanation":"The suffix '-tion' turns a verb into a noun and makes a /shun/ sound.","words":["action","injection","competition","education","nation"]},
    {"id":"y2s34","year":"Year 2","step":34,"title":"Year 2 - Step 34: Contractions","explanation":"Contractions are shortened forms of words using apostrophes.","words":["can't","didn't","I'll","she's","won't"]},
    {"id":"y2s36","year":"Year 2","step":36,"title":"Year 2 - Step 36: Challenge Words","explanation":"These words have unusual patterns.","words":["whole","any","many","clothes","busy"]},
]


def default_state():
    return {
        'pupils': [],
        'rules': DEFAULT_RULES,
        'weeks': [],
        'currentWeek': None,
        'adaptedPupils': [],
        'hlContent': {'maths': '', 'reading': '', 'mathsAdapted': '', 'readingAdapted': '', 'label': ''},
    }